# Generated by Django 4.2.7 on 2023-11-30 00:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('service_name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('pricemin', models.DecimalField(decimal_places=0, max_digits=5, null=True, verbose_name='Цена от')),
                ('pricemax', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Цена до')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('languages', models.CharField(blank=True, max_length=100, null=True, verbose_name='Языки помимо русского')),
                ('about', models.TextField()),
                ('photo', models.ImageField(upload_to='media/masters', verbose_name='Фото')),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='media/gallery', verbose_name='Фото ваших работ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Категория')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='Город')),
            ],
            options={
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.master')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Услуга'),
        ),
        migrations.CreateModel(
            name='GalleryPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/gallery/')),
                ('master', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.master', verbose_name='Master')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
    ]
