# Generated by Django 4.2.7 on 2023-11-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231130_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypicture',
            name='image',
            field=models.ImageField(upload_to='profisrael/media/gallery/'),
        ),
    ]
