# Generated by Django 4.2.7 on 2023-11-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gallerypicture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
